name: Mobile CI/CD

on:
  push:
    branches: [main, develop]
    paths: ['apps/mobile/**', 'packages/shared/**']
  pull_request:
    branches: [main]
    paths: ['apps/mobile/**', 'packages/shared/**']

jobs:
  test-mobile:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm ci

      - name: Run tests
        run: |
          cd apps/mobile
          npm run test -- --coverage --watchAll=false

      - name: Run TypeScript check
        run: |
          cd apps/mobile
          npx tsc --noEmit

      - name: Run ESLint
        run: |
          cd apps/mobile
          npm run lint

  build-android:
    needs: test-mobile
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm ci

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android
        run: |
          cd apps/mobile
          expo build:android --type apk --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: apps/mobile/*.apk

  build-ios:
    needs: test-mobile
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm ci

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS
        run: |
          cd apps/mobile
          expo build:ios --type archive --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Upload iOS Archive
        uses: actions/upload-artifact@v3
        with:
          name: ios-archive
          path: apps/mobile/*.ipa